export const ENDPOINTS = {
  LOGIN_ENDPOINT: "/admin/login",
  AUTHENTICATE_ENDPOINT: "/admin/authenticate",
  GET_TUTOR_BY_ID: "/admin/tutors/",
  GET_ALL_TUTORS: "/admin/tutors",
  GET_ALL_RESERVATIONS: "/admin/reservations",
  GET_SUBJECTS_ENDPOINT: "/job/get_all_subjects",
  GET_TAGS_ENDPOINT: "/job/get_all_tags",
  APPROVE_TUTOR_ENDPOINT: "/admin/tutors/approve",
  ADD_COMMENT_ENDPOINT: "/admin/tutors/add_comment",
  ADD_SUBJECT_ENDPOINT: "/admin/jobs/subjects",
  ADD_TAG_ENDPOINT: "/admin/jobs/tags",
  GET_JOB_BY_ID_ENDPOINT: (id: number) => `/job/${id}`,
  MARK_REFUND_ENDPOINT: "/admin/reservations/mark_refund",
  UPLOAD_FILE_ENDPOINT: "/admin/files/upload",
  MANUAL_REFUND: "/admin/reservations/manual_refund",
  JOBS_PRETTY_PRINT: "/admin/jobs/pretty_print",
  LIST_RESERVATION_SLIP: "/admin/reservations/list_slip",
  APPROVE_SLIP: "/admin/reservations/approve_slip",
  REFERRAL_CODES: "/admin/referral/code",
  JOB_SUMMARY: "/admin/jobs/summary",
};
